/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import conexao.Conexao;
import dao.InseminadorDao;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import model.Ins_situacao;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Lest
 */
public class Report extends javax.swing.JFrame {

    /**
     * Creates new form Report
     * 
     */
        int mouse = 0;
        Connection conn = null;

    public Report() {
        initComponents();

        
        /*/DefaultTableModel da = new DefaultTableModel();
        da.addColumn("Nome");
        da.addColumn("Raça");
        String sql = "SELECT t.nome,r.descricao FROM touro t JOIN raca r ON r.codigo = t.cod_raca;";
        PreparedStatement ps;
        try {
            ps = conexao.Conexao.getConexao().prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                String[] linha = {rs.getString("nome"),rs.getString("descricao")};
                da.addRow(linha);
                }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(InseminadorDao.class.getName()).log(Level.SEVERE, null, ex);
        }
        tabela.setModel(da);
        /*/
    }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RelatorioVacasNormais = new javax.swing.JButton();
        RelatorioVacasPrenhas = new javax.swing.JButton();
        RelatorioProducao = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RelatorioVacasNormais.setText("Relatório Vacas Normais");
        RelatorioVacasNormais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelatorioVacasNormaisActionPerformed(evt);
            }
        });

        RelatorioVacasPrenhas.setText("Relatório Vacas Prenhas");
        RelatorioVacasPrenhas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelatorioVacasPrenhasActionPerformed(evt);
            }
        });

        RelatorioProducao.setText("Relatório de Produção");
        RelatorioProducao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelatorioProducaoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Relatórios");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RelatorioProducao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RelatorioVacasPrenhas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RelatorioVacasNormais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(RelatorioVacasNormais, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RelatorioVacasPrenhas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RelatorioProducao, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        mouse++;
        if(mouse == 3){
            try{
                conn=Conexao.getConexao();

            }catch(SQLException | ClassNotFoundException ex){
                System.out.println("deu ruim");
            }
            String src = "Relatório de vacas estranhas.jasper"; // o da producao do mes/ano depende do que a véia botar

            JasperPrint jasperPrint = null;
             try {
                 jasperPrint = JasperFillManager.fillReport(src,null,conn);
                 //jasperPrint = JasperFillManager.fillrep
             } catch (JRException ex) {
                 Logger.getLogger(Report.class.getName()).log(Level.SEVERE, null, ex);
             }

            JasperViewer view = new JasperViewer(jasperPrint, false);
            view.setVisible(true);
                conexao.Conexao.fechaConexao();
        }
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void RelatorioVacasNormaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatorioVacasNormaisActionPerformed
        // TODO add your handling code here:
        try{
                conn=Conexao.getConexao();

            }catch(SQLException | ClassNotFoundException ex){
                System.out.println("deu ruim");
            }
            String src = "Relatorio de vacas normais.jasper"; // o da producao do mes/ano depende do que a véia botar

            JasperPrint jasperPrint = null;
             try {
                 jasperPrint = JasperFillManager.fillReport(src,null,conn);
                 //jasperPrint = JasperFillManager.fillrep
             } catch (JRException ex) {
                 Logger.getLogger(Report.class.getName()).log(Level.SEVERE, null, ex);
             }

            JasperViewer view = new JasperViewer(jasperPrint, false);
            view.setVisible(true);
            conexao.Conexao.fechaConexao();
    }//GEN-LAST:event_RelatorioVacasNormaisActionPerformed

    private void RelatorioVacasPrenhasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatorioVacasPrenhasActionPerformed
        // TODO add your handling code here:
        try{
                conn=Conexao.getConexao();

            }catch(SQLException | ClassNotFoundException ex){
                System.out.println("deu ruim");
            }
            String src = "Relatorio de vacas prenhas.jasper"; // o da producao do mes/ano depende do que a véia botar

            JasperPrint jasperPrint = null;
             try {
                 jasperPrint = JasperFillManager.fillReport(src,null,conn);
                 //jasperPrint = JasperFillManager.fillrep
             } catch (JRException ex) {
                 Logger.getLogger(Report.class.getName()).log(Level.SEVERE, null, ex);
             }

            JasperViewer view = new JasperViewer(jasperPrint, false);
            view.setVisible(true);
            conexao.Conexao.fechaConexao();
    }//GEN-LAST:event_RelatorioVacasPrenhasActionPerformed

    private void RelatorioProducaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatorioProducaoActionPerformed
        SelecionarDataView form = new SelecionarDataView();
        form.setLocationRelativeTo(null);
        form.setVisible(true);
    }//GEN-LAST:event_RelatorioProducaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RelatorioProducao;
    private javax.swing.JButton RelatorioVacasNormais;
    private javax.swing.JButton RelatorioVacasPrenhas;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
